if(NOT PKG_CONFIG_FOUND)
    INCLUDE(FindPkgConfig)
endif()
message(STATUS "++++PKG_CHECK")
PKG_CHECK_MODULES(PC_GNURADIO_IIO gnuradio-iio)
message(STATUS "++++++++ GnuradioIIO, ${PC_GNURADIO_IIO_INCLUDEDIR} ++ ${PC_GNURADIO_IIO_LIBDIR}")
FIND_PATH(
    GNURADIO_IIO_INCLUDE_DIRS
    NAMES iio/api.h
    HINTS $ENV{GNURADIO_IIO_DIR}/include
        ${PC_GNURADIO_IIO_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GNURADIO_IIO_LIBRARIES
    NAMES gnuradio-iio
    HINTS $ENV{GNURADIO_IIO_DIR}/lib
        ${PC_GNURADIO_IIO_LIBDIR}
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

if(GNURADIO_IIO_INCLUDE_DIRS AND GNURADIO_IIO_LIBRARIES)
  set(GNURADIO_IIO_FOUND TRUE CACHE INTERNAL "gnuradio-iio found")
  message(STATUS "Found gnuradio-iio: ${GNURADIO_IIO_INCLUDE_DIRS}, ${GNURADIO_IIO_LIBRARIES}")
else(GNURADIO_IIO_INCLUDE_DIRS AND GNURADIO_IIO_LIBRARIES)
  set(GNURADIO_IIO_FOUND FALSE CACHE INTERNAL "gnuradio-iio not found")
  message(STATUS "gnuradio-iio not found.")
endif(GNURADIO_IIO_INCLUDE_DIRS AND GNURADIO_IIO_LIBRARIES)

MARK_AS_ADVANCED(GNURADIO_IIO_LIBRARIES GNURADIO_IIO_INCLUDE_DIRS)

